### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/mcpilauncher#4]
Features:

- [ ] Move from SDL 1.2 to SDL 2

	- Improved Game Controller API

	- Improved fullscreen support

	- Clipboard support

	- zlib instead of LGPL

- [x] Add fullscreen support

- [ ] Add clipboard support

- [ ] Add game controller support

- [ ] Packaging; i.e.: Flatpak or the like to allow people to easily run it

Fixes:

- [ ] Fix crashing when the game tries to load worlds from the directory

- [x] Have the game run at the size of the window (will this break things?)

- [ ] Pointer size assertions

- [ ] Jail glEnable, glDisable and glEnableClientState to avoid undefined behaviour with inconsistencies accross desktop EGL and Raspberry Pi's EGL

- [ ] README that describes how to set up

- [ ] Ensure multiplayer and the scripting system work properly

- [ ] Remove QEMU from the source tree, possibly have it be a patch?

**Comment by lukeeey** [comment]
Couldn't this technically be run on Android since its also ARM.

**Comment by mhsjlw** [comment]
There's no point as this is just Minecraft PE edition modified and repackaged for the RPI. However, as it uses QEMU you could run this on a MIPS PC or any other supported QEMU host architecture

**Comment by JayFoxRox** [comment]
As it uses linux-user it will only work on Linux hosts at this point though. But theoretically, it's possible to develop this further with full syscall hooking, and it can be made to work cross-platform (with or without the CPU emulation layer).

Running on ARM or especially mobile devices (in the current form) is actually an issue at this point, because the QEMU layer probably adds a lot of computational overhead. So you'd either experience slowdown or quickly drain your battery.

**Comment by mhsjlw** [comment]
In the far future, I plan on switching to [dynarmic](https://github.com/MerryMage/dynarmic) and hooking `bl*` and `svc*` syscalls to enable major speed ups and cross platform support (although, it will only work on x86_64 platforms, I do not see this as a problem, though). It would be a big project and is currently not possible. The QEMU solution we are using now is quite good in my opinion, but I have a couple of ideas on how to remove the QEMU repository from this one. Besides, there is many more things I need to fix than this, and this TODO will be split into multiple issues in the future with priority tags.

**Comment by mhsjlw** [comment]
I had the opportunity to test this out on another piece of hardware, some interesting things happened:
- The toolbar actually rendered (it doesn't on my system)
- World listing didn't lock up the game (it does on my system)

This leads me to believe that I've wrecked my build on my system or something along those lines, I'll try to rebuild fresh and see what happens.

**Comment by mhsjlw** [comment]
Moving these to their own issues
